---
kind: 'pipeline'
name: 'build'
type: 'kubernetes'

steps:

# build and publish
- image: 'docker.io/plugins/docker'
  name: 'publish'
  pull: 'always'
  settings:

    # registery and repos
    registry: 'docker.io'
    repo: 'rakepanorama/simoncor-net'
    mtu: '1440'

    # build stuff
    dockerfile: 'Dockerfile.linux.amd64'
    daemon_off: 'false'

    # authentication
    username:
      from_secret: 'docker_username'
    password:
      from_secret: 'docker_password'

    # tags
    tags:
    - 'v1'
    - 'latest'
