FROM cr.simoncor.net/siempie/hugo-sws:latest

# clone site and template
COPY . /src

# generate site
RUN set -e \
      && /usr/local/bin/hugo --source=/src/

# copy public content
RUN set -e \
      && cp -r /src/public /site/

# cleanup
RUN set -e \ 
      && rm -rf /src

# expose 80
EXPOSE 80

# start static-web-server
ENTRYPOINT ["/usr/local/bin/sws", "--host=0.0.0.0", "--log-level=info", "--port=80", "--root=/site/"]
