---

variables:
  STORAGE_DRIVER: "overlay"

stages:
  - "build"

build:
  stage: "build"
  image: "quay.io/buildah/stable:latest"
  script:

    # login
    - "echo $CR_PASSWORD | buildah login -u $CR_USERNAME --password-stdin $CR_HOSTNAME"

    # build image
    - "buildah bud -t simoncor-net -f Dockerfile.linux.amd64 ."

    # tag image
    - "buildah tag simoncor-net cr.simoncor.net/siempie/simoncor-net:latest"

    # push image
    - "buildah push cr.simoncor.net/siempie/simoncor-net:latest"

    # logout
    - "buildah logout $CR_HOSTNAME"
