---

variables:
  STORAGE_DRIVER: "overlay"
  IMAGE_TAG: "simoncor-net"

stages:
  - "build"

build:
  stage: "build"
  image: "quay.io/buildah/stable:latest"
  script:

    # login to container registry
    - "echo $CI_REGISTRY_PASSWORD | buildah login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY"

    # build image
    - "buildah bud -t $IMAGE_TAG -f Dockerfile.linux.amd64 ."

    # add tags to image
    - "buildah tag $IMAGE_TAG $CI_REGISTRY_IMAGE:latest"

    # push image
    - "buildah push $CI_REGISTRY_IMAGE:latest"

    # logout from container registry
    - "buildah logout $CI_REGISTRY"
